apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: an14hyqbj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: an14hyqbj-python 
  name: an14hyqbj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: an14hyqbj-python 
