apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: an14hyqbj-python 
  janus-idp.io/tekton: an14hyqbj-python
  backstage.io/kubernetes-id: an14hyqbj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: an14hyqbj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml