apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: an14hyqbj-python-gitops
  description: This is GitOps manifest for an14hyqbj-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=an14hyqbj-python
    backstage.io/kubernetes-id: an14hyqbj-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: an14hyqbj-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:an14hyqbj-python
